### ISSUE TITLE
docker-compose fails because of missing docker image

### ISSUE THREAD

**Issue by georgasa** [smallstep/step-sds#6]
Hello.

I was trying to build your product according to your instructions but it fails as it can't find the appropriate docker file for the sds service:

Building sds
Step 1/9 : FROM smallstep/step-sds:latest
Trying to pull repository docker.io/smallstep/step-sds ... 
ERROR: Service 'sds' failed to build: repository docker.io/smallstep/step-sds not found: does not exist or no pull access

Can you please advise how should I proceed?

Thank you,
Apostolos

**Comment by maraino** [comment]
Hi @georgasa, we haven't "officially released" this product yet, and you are able to run the tests locally if you first do `make docker`. But to make things easier I'm gonna do an initial release so you can run it with just docker-compose.

I've closed the issue when it's done.

**Comment by maraino** [comment]
Hello again @georgasa, I've pushed an image to [docker](https://hub.docker.com/r/smallstep/step-sds/tags), so now `docker-compose up` should work without any pre-requisites.

Salut,
Mariano

**Comment by maraino** [comment]
Let us know if you find something.

**Comment by georgasa** [comment]
Thank you very much for your prompt actions. The docker-compose deployment is now successful. I needed only to change the envoyproxy/envoy-alpine to the specific envoyproxy/envoy-alpine:v1.14.1 as I could't download the former one.

I'll play a little with the SDS server and I'll let you know if I find something.

Thanks,
Apostolos
